repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
        args: [ '--maxkb=500' ]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
      - id: check-merge-conflict
      - id: check-yaml
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args:
          - --ignore
          - DL3008
          - --ignore
          - DL3018
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.1
    hooks:
      - id: gitleaks
        args: [ '--verbose' ]
