services:
  api:
    build: ./api
    image: kvdomingo/fastcord-api
    init: true
    env_file: ./api/.env
    volumes:
      - ./api:/app
      - venv-data:/app/.venv
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/ready" ]
      interval: 20s
      start_interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 8000:8000

  ui:
    image: oven/bun:1.1-alpine
    init: true
    environment:
      NODE_ENV: development
    working_dir: /app
    volumes:
      - ./ui:/app
    entrypoint:
      - /bin/sh
      - "-c"
      - "bun install && exec bun run dev"
    ports:
      - 3000:3000
    depends_on:
      api:
        condition: service_healthy

  db:
    build:
      context: .
      dockerfile: pg.Dockerfile
    image: ghcr.io/kvdomingo/postgresql:bitnami-16.4.0-debian-12-r23-pg_idkit-0.2.3
    env_file: ./api/.env
    volumes:
      - db-data:/bitnami/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRESQL_USERNAME}" ]
      interval: 20s
      timeout: 5s
      retries: 3
    ports:
      - 5432:5432

volumes:
  db-data:
  venv-data:
