version: '3'

vars:
  COMMIT_SHA:
    sh: git rev-parse --short HEAD

tasks:
  default:
    cmd:
      task: up

  init:
    desc: Initial setup
    cmds:
      - mise install --yes
      - pip install -U pre-commit
      - pre-commit install
      - cd api && uv sync && cd ..
      - cd ui && bun install && cd ..

  up:
    desc: Build and start containers
    cmd: infisical run -- docker compose up --detach --build --remove-orphans {{ .CLI_ARGS }}

  psql:
    desc: Access postgres cli
    cmd: docker compose exec -- postgres psql -U postgres

  exec:
    desc: Execute command in specified container
    cmd: docker compose  exec -- {{ .CLI_ARGS }}

  restart:
    desc: Restart all containers
    cmd: docker compose restart {{ .CLI_ARGS }}

  logs:
    desc: Show Docker logs
    interactive: true
    cmd: docker compose logs --follow {{ .CLI_ARGS }}

  stop:
    desc: Stop all containers
    cmd: docker compose stop {{ .CLI_ARGS }}

  clean:
    desc: Stop and remove all containers
    cmd: docker compose down --volumes --remove-orphans

  makemigrations:
    desc: Create database migrations
    dir: api
    cmd: uv run alembic revision -m "{{ .CLI_ARGS }}"

  migrate:
    desc: Apply database migrations
    dir: api
    cmd: task exec -- api uv run alembic upgrade head

  unmigrate:
    desc: Undo database migrations
    dir: api
    cmd: task exec -- api uv run alembic downgrade -1
