# Generated by Django 5.0.7 on 2024-07-20 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import api.models.base


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Guild",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=api.models.base.generate_cuid,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                ("avatar", models.ImageField(max_length=255, upload_to="")),
                ("banner", models.ImageField(max_length=255, upload_to="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChannelGroup",
            fields=[
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=api.models.base.generate_cuid,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=32)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_groups",
                        to="api.guild",
                    ),
                ),
            ],
            options={
                "ordering": ["guild", "order"],
            },
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=api.models.base.generate_cuid,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=32)),
                (
                    "type",
                    models.CharField(
                        choices=[("TEXT", "Text"), ("VOICE", "Voice")],
                        default="TEXT",
                        max_length=8,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="channels",
                        to="api.channelgroup",
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="api.guild",
                    ),
                ),
            ],
            options={
                "ordering": ["guild", "group", "order"],
            },
        ),
        migrations.CreateModel(
            name="UserGuildOrder",
            fields=[
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=api.models.base.generate_cuid,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.guild"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user", "order"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=api.models.base.generate_cuid,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("discriminator", models.PositiveSmallIntegerField()),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to=""
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to=""
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("DO_NOT_DISTURB", "Do Not Disturb"),
                            ("IDLE", "Idle"),
                            ("OFFLINE", "Offline"),
                        ],
                        default="ONLINE",
                        max_length=16,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__username"],
                "unique_together": {("user", "discriminator")},
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=api.models.base.generate_cuid,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("content", models.TextField(max_length=2048)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="api.channel",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="api.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Emoji",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=api.models.base.generate_cuid,
                        editable=False,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=16)),
                ("source", models.ImageField(max_length=255, upload_to="")),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emojis",
                        to="api.guild",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emojis",
                        to="api.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["guild", "-created"],
            },
        ),
    ]
