# Generated by Django 5.0.7 on 2024-07-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoji',
            name='name',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='guild',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
